export interface CreditoResponse {
    id: number,
    montoPrestamo: number,
    saldoFinanciar: number,
    tipoTasaInteres: string,
    tasaInteres: number,
    teaOriginal: number,
    frecuenciaPago: string,
    fechaInicio: string,
    bonoBuenPagador: number,
    tipoPeriodoGracia: string,
    periodoGracia: number,
    pCuotaInicial: number,
    numeroAnios: number,
    numeroDiasxAnio: number,
    ncuotasxAnio: number,
    ntotalCuotas: number,
    seguroDegPerd: number,
    seguroRiesgoPerd: number,
    tasaDescuento: number,
    idUsuario: number,
    idEntidadFinanciera: number,
    idInmueble: number
}